version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8080"

    environment:
      DB_HOST: db
      DB_NAME: recdb
      DB_USER: devuser
      DB_PASS: P@ssw0rd
    depends_on:
      - db

  db:
    image: postgres:alpine
    expose:
      - 5433
    ports:
      - "5433:5433"
    container_name: db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: recdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: P@ssw0rd
    command: -p 5433
volumes:
  postgres-data:
