# pytest-django
[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "app.settings"
python_files = ["test_*.py"]

# ruff
[tool.ruff]
line-length = 88
exclude = [
   "migrations",
    "__pycache__",
    "manage.py",
    "settings.py"
]
