---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Testing and Linting
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Ruff
        uses: chartboost/ruff-action@v1

      - name: Black
        uses: psf/black@stable

      - name: Tests
        run: docker-compose run --rm app sh -c "python manage.py test"
